FROM node:16-alpine

WORKDIR '/app'

# COPY --chown=node:node package.json . 
COPY package.json . 
RUN npm install
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

# COPY --chown=node:node . .
COPY . .

CMD ["npm", "run", "start"]